name: xtoys-health-plugin
version: 1.0
main: com.xqueezeme.xtoys.health.plugin.XToysHealthPlugin
commands:
  xtoys-register:
    description: registers your xtoys wekhookId
    usage: /xtoys-register <WEBHOOK_ID>
  xtoys-unregister:
    description: Removes your xtoys wekhookId
    usage: /xtoys-unregister
  xtoys-enable:
    description: Enables the plugin for a player
    usage: /xtoys-enable
  xtoys-disable:
    description: Disables the plugin for a player
    usage: /xtoys-disable